name: elibrary
description: "HSEP e-library mobile app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  intl: ^0.18.1
  flutter_svg: ^2.0.9
  http: ^1.2.0
  syncfusion_flutter_pdfviewer: ^24.1.46
  wakelock_plus: ^1.1.4
  path_provider: ^2.1.2
  permission_handler: ^10.2.0
  mime: ^1.0.4
  device_info_plus: ^9.1.1
  saf: ^1.0.3+4
  share_plus: ^7.2.1
  rxdart: ^0.27.7
  webview_flutter: ^4.4.4
  lottie: ^3.0.0
  html_editor_enhanced: ^2.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          style: normal

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          style: normal

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          style: normal