name: elibrary
description: "HSEP e-library mobile app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  get: ^4.6.6
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  intl: ^0.18.1
  flutter_svg: ^2.0.9

  dio: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          style: normal

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          style: normal

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          style: normal